config/routes.rb
Rails.application.routes.draw do
  resources :users, :except => [:new, :create] do
    resources :events, :except => [:new]
  end

  resources :friends, :except => [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'
  
  #Signup Routes
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'


  # Login and Logout Routes
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/friend.rb
class Friend < ApplicationRecord
    has_many :events, :dependent => :delete_all
    has_many :user_friends, :dependent => :delete_all
    has_many :users, :through => :user_friends
    validates_presence_of :first_name, :last_name, :birthday_month, :birthday_day
    validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: "is invalid"
    validates_format_of :phone, :with => /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/

    validates :birthday_month, inclusion: {in: %w(January February March April May June July August September October November December), message: "Must be a valid month"}

    validates :birthday_day, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 31, :message => "can only be number between 1 and 31." }
    scope :birthdays_soon, -> {where(birthday_month: Date::MONTHNAMES[Date.today.month])}
    scope :birthdays_future, -> {birthdays_soon.where("birthday_day >= ?", Date.today.day)}

    def full_name
        first_name + " " + last_name
    end

    def birthday
        "#{birthday_month} #{birthday_day}"
    end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    before_action :find_friend, only: [:edit, :update, :show, :destroy]


    def new
        @friend = current_user.friends.build
    end
    
    def create
        @friend = Friend.new(friend_params)
        if @friend.save
            @uf = UserFriend.create(friend_id: @friend.id, user_id: current_user.id)
            redirect_to user_path(current_user)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if current_user.friends.include?(@friend)
         if @friend.update(friend_params)
            redirect_to friend_path(@friend)
         else
            render :edit
         end
        else
            render :edit
        end
    end

    def destroy
        if current_user.friends.include?(@friend)
            @friend.destroy
            redirect_to user_path(current_user)
        else
            render :show, notice: "Cannot delete"
        end
    end

    private

    def friend_params
        params.require(:friend).permit(
            :first_name,
            :last_name,
            :phone,
            :email,
            :birthday_month,
            :birthday_day
        )
    end

    def find_friend
        @friend = Friend.find(params[:id])
    end

end

app/helpers/friends_helper.rb
module FriendsHelper
    def display_friends(user)
        @friends = user.friends
        if logged_in? && current_user == user
            render partial: "users/detailed_friends", locals: {user: user, friends: @friends}
        else
            render partial: "users/basic_friends", locals: {friends: @friends}
        end
    end
end

app/views/friends/_form.html.erb
<%= form_with model: friend, local: true do |f| %>

<% if friend.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(friend.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% friend.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.label :first_name, "First Name:" %>
<%= f.text_field :first_name %>

<%= f.label :last_name, "Last Name:" %>
<%= f.text_field :last_name %> <br> <br>

<%= f.label :email, "Email:" %>
<%= f.text_field :email %> <br> <br>

<%= f.label :phone, "Phone:" %>
<%= f.text_field :phone %> <br> <br>

<%= f.label :birthday_month, "Birthday Month:" %>
<%= f.collection_select :birthday_month, Date::MONTHNAMES[1..12], :strip, :strip %> <br> <br>

<%= f.label :birthday_day, "Birthday Day:" %>
<%= f.collection_select :birthday_day, [*1..31], :to_s, :to_s %> <br> <br>

<%= submit_tag %>
<% end %>

app/views/friends/edit.html.erb
<%= render partial: "form", locals: {friend: @friend} %>

app/views/friends/new.html.erb
<%= render partial: "form", locals: {friend: @friend} %>

app/views/friends/show.html.erb
<h1> <%= @friend.full_name %></h1> 

<div>
Birthday Info: <%= @friend.birthday %>
</div>
<br>

<div>
<h2> Contact Info </h2>
<ul>
    <li> Phone: <%= @friend.phone %> </li>
    <li> Email: <%= @friend.email %> </li>
</ul>
</div>

<%= button_to 'Edit', edit_friend_path(@friend), method: "get" %>
<%= button_to 'Delete', friend_path(@friend), method: "delete" %>