config/routes.rb
Rails.application.routes.draw do
  resources :users, :except => [:new, :create] do
    resources :events, :except => [:new]
  end

  resources :friends, :except => [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'
  
  #Signup Routes
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'


  # Login and Logout Routes
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :events, :dependent => :delete_all
    has_many :user_friends, :dependent => :delete_all
    has_many :friends, :through => :user_friends
    has_many :comments, :dependent => :delete_all
    has_many :commented_events, :through => :comments, :source => :event

    validates_presence_of :first_name, :last_name, :email
    validates :email, uniqueness: true

    validates_format_of :email, with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: "is invalid"

    def full_name
        first_name + " " + last_name
    end
 
    def upcoming_birthdays
      self.friends.birthdays_future
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate_user!, only: [:new, :create]
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @event = @user.events.build
    end

    def edit

    end

    def update
        if @user == current_user && @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        if @user == current_user
            @user.destroy
            reset_session
            redirect_to root_path
        else
            render :show
        end
    end

    private

    def user_params
        params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation
        )
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def show_add_event
        if current_user_viewing_self
            if @user.friends.any?
                render "users/add_event"
            else
                render "users/need_friend"
            end
        end
    end
end

app/views/users/_add_event.html.erb
<h2> Add an Event </h2>
<%= form_with model: @event, url: user_events_path(@user), method: "post", local: true do |f|%>
<% if @event.errors.any? %>
        <div id="error_explanation">
          <h4>
            <%= pluralize(@event.errors.count, "error") %> prohibited
            this event from being saved:
          </h4>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

<%= f.hidden_field :user_id %>
<div>
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div>
<%= f.label :location %>
<%= f.text_field :location %>
</div>

<div>
<%= f.label :friend_id %>
<%= f.collection_select :friend_id, @event.user.friends, :id, :full_name, prompt: true %>
</div>

<div>
<%= f.label :event_time %>
<%= f.datetime_field :event_time %>
</div>

<div>
<%= f.submit %>
</div>


<% end %>

app/views/users/_basic_friends.html.erb
<h2> Friends </h2>
<ul>
<% friends.each do |friend| %>
    <li> <%= friend.full_name %> </li>
<% end %>
</ul>

app/views/users/_detailed_friends.html.erb
<h2> Friends </h2>
<%= button_to "Add a Friend", new_friend_path, method: "get" %>
<ul>
<% friends.each do |friend| %>
    <li> <%= link_to friend.full_name, friend_path(friend)  %> 
        <ul>
            <li> Phone: <%= friend.phone %> </li>
            <li> Email: <%= friend.email %> </li>
            <li> Birthday: <%= friend.birthday %> </li>
        </ul>
    </li>
<% end %>
</ul> <br> <br>

<h2> Upcoming Birthdays This Month </h2>
<ul>
<% user.upcoming_birthdays.each do |friend| %>
    <li> <%= friend.full_name + " - " + friend.birthday %> </li>
<% end %>
</ul>
    

app/views/users/_need_friend.html.erb
<h2>Events</h2>
<p>Add a Friend Above Before Creating an Event</p>

app/views/users/edit.html.erb
<h1> Update User </h1>

<%= form_with model: @user, local: true do |f| %>

<% if @user.errors.any? %>
        <div id="error_explanation">
          <h4>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

<%= f.label :first_name, "First Name:" %>
<%= f.text_field :first_name %>

<%= f.label :last_name, "Last Name:" %>
<%= f.text_field :last_name %> <br> <br>

<%= f.label :email, "Email:" %>
<%= f.text_field :email %> <br> <br>

<%= submit_tag %>

<% end %>

app/views/users/new.html.erb
<h1> Signup </h1>
<%= form_with model: @user, url:"/signup", method: "post", local: true do |f| %>

<% if @user.errors.any? %>
        <div id="error_explanation">
          <h4>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

<%= f.label :first_name, "First Name:" %>
<%= f.text_field :first_name %>

<%= f.label :last_name, "Last Name:" %>
<%= f.text_field :last_name %> <br> <br>

<%= f.label :email, "Email:" %>
<%= f.text_field :email %> <br> <br>

<%= f.label :password, "Password:" %>
<%= f.password_field :password %> <br> <br>

<%= f.label :password_confirmation, "Password Confirmation:" %>
<%= f.password_field :password_confirmation %> <br> <br>

<%= submit_tag "Signup"%>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.full_name %> </h1>

<% if current_user_viewing_self %>
<%= button_to "Edit User", edit_user_path(@user), method: "get", class: "account-buttons" %>
<%= button_to "Delete Account", user_path(@user), method: "delete", class: "account-buttons" %>
<%end%>

<br>

<%= display_friends(@user) %>

<%= show_add_event %>