config/routes.rb
Rails.application.routes.draw do
  resources :users, :except => [:new, :create] do
    resources :events, :except => [:new]
  end

  resources :friends, :except => [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'
  
  #Signup Routes
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'


  # Login and Logout Routes
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    belongs_to :friend
    has_many :comments, :dependent => :delete_all
    has_many :commenting_users, through: :comments, source: :user

    validates_presence_of :title, :location, :event_time
    validates :title, length: {maximum: 20}

    def readable_time
        event_time.strftime("%A, %d %b %Y %l:%M %p")
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :find_event, only: [:edit, :update, :show, :destroy]

    def new
        @event = current_user.events.build
    end

    def create
        @event = Event.new(event_params)
        if @event.save
            redirect_to user_event_path(@event.user, @event)
        else
            @user = @event.user
            render '/users/show'
        end

    end

    def edit
        @user = @event.user
        if @user != current_user
            redirect_to user_path(current_user), notice: "You cannot view details of events of another user"
        end
    end

    def update
        if current_user.events.include?(@event)
         if @event.update(event_params)
            redirect_to user_event_path(@event.user, @event)
         else
            render :edit
         end
        else
            render :edit
        end
    end


    def show
        if @event.user != current_user
            redirect_to user_path(current_user), notice: "You cannot view details of events of another user"
        end

    end

    def index
        @user = User.find(params[:user_id])
        if current_user == @user
            @events = @user.events
        else
            redirect_to user_path(@user), notice: "You cannot view events of another user"
        end
    end

    def destroy
        @event.destroy if @event.user = current_user
        redirect_to user_path(current_user)
    end

    private

    def event_params
        params.require(:event).permit(
            :location,
            :title,
            :event_time,
            :user_id,
            :friend_id
        )
    end

    def find_event
        @event = Event.find(params[:id])
    end

end

app/views/events/_form.html.erb
<%= form_with model: @event, url: user_event_path(@event.user_id, @event), local: true do |f|%>
<% if @event.errors.any? %>
        <div id="error_explanation">
          <h4>
            <%= pluralize(@event.errors.count, "error") %> prohibited
            this event from being saved:
          </h4>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

<%= f.hidden_field :user_id %>
<div>
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div>
<%= f.label :location %>
<%= f.text_field :location %>
</div>

<div>
<%= f.label :friend_id %>
<%= f.collection_select :friend_id, @event.user.friends, :id, :full_name, prompt: true %>
</div>

<div>
<%= f.label :event_time %>
<%= f.datetime_field :event_time %>
</div>

<div>
<%= f.submit %>
</div>


<% end %>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/index.html.erb
<h1> Events </h1>

<ul>
<% @user.events.each do |event|%>
<li> <%= link_to event.title, user_event_path(@user,event) %>
    <ul>
        <li>Friend: <%= event.friend.full_name %></li>
        <li>Location: <%= event.title %></li>
        <li>Event Time: <%= event.readable_time %></li>

    </ul>
</li>

<%end %>
</ul>

app/views/events/show.html.erb
<h1> <%= @event.title %> </h1>
<ul>
    <li>Friend: <%= link_to @event.friend.full_name, friend_path(@event.friend) %></li>
    <li>Location: <%= @event.title %></li>
    <li>Event Time: <%= @event.readable_time %></li>

 </ul>

 <%= button_to "Edit Event", edit_user_event_path(@event.user, @event), method: "get" %> 
 <br>
 <%= button_to "Delete Event", user_event_path(@event.user, @event), method: "delete" %>